mongo:
  build: mongodb/
  container_name: ks_mongodb
  environment:
    MONGO_INITDB_DATABASE: knowprod
  expose:
    - 27017

ks_api:
  build: app/
  container_name: ks_app
  links:
    - mongo
  ports:
    - 8081:8081
  volumes:
    - ./app/KS-API/:/app/KS-API

ks_web:
  image: nginx:1.13
  container_name: ks_web
  ports:
    - 80:80
    - 443:443
  volumes:
    - ./web/nginx.conf:/etc/nginx/nginx.conf
    - ./web/dist/:/usr/share/nginx/html
    - ./web/ssl/:/etc/nginx/ssl

cadvisor:
  image: google/cadvisor:latest
  ports:
    - 8080:8080
  volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro