mongo:
  build: mongodb/
  container_name: ks_mongodb
  environment:
    MONGO_INITDB_DATABASE: knowprod
  ports:
    - 27017:27017

ks_api:
  build: app/
  container_name: ks_app
  links:
    - mongo
  ports:
    - 8081:8081